In [6]:
# Install necessary packages
!pip install numpy
!pip install pandas

In [9]:
# Load packages
import numpy as np
import pandas as pd

In [11]:
!pip show numpy

Name: numpy
Version: 1.23.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\ksp\appdata\local\programs\python\python310\lib\site-packages
Requires: 
Required-by: pandas


In [38]:
np.__version__

'1.23.3'

In [4]:
# Load cars price dataset
cars_price = pd.read_csv("./cars_price_dataset.csv")

## Question 2:

In [5]:
# How many records are in the dataset?
cars_price.shape

(11914, 16)

## Question 3:

In [17]:
# Who are the most frequent car manufacturers (top-3) according to the dataset?
cars_price.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [50]:
cars_price["Make"].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

**Chevrolet**, **Ford** and **Volkswagen** are the top 3 car manufacturers as per the dataset.

## Question 4:

In [31]:
# What's the number of unique Audi car models in the dataset?
audi = cars_price[cars_price["Make"] == "Audi"]
audi.head()

Make Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
17  Audi   100  1992  regular unleaded      172.0               6.0   
18  Audi   100  1992  regular unleaded      172.0               6.0   
19  Audi   100  1992  regular unleaded      172.0               6.0   
20  Audi   100  1992  regular unleaded      172.0               6.0   
21  Audi   100  1992  regular unleaded      172.0               6.0   

   Transmission Type      Driven_Wheels  Number of Doors Market Category  \
17            MANUAL  front wheel drive              4.0          Luxury   
18            MANUAL  front wheel drive              4.0          Luxury   
19         AUTOMATIC    all wheel drive              4.0          Luxury   
20            MANUAL  front wheel drive              4.0          Luxury   
21            MANUAL    all wheel drive              4.0          Luxury   

   Vehicle Size Vehicle Style  highway MPG  city mpg  Popularity  MSRP  
17      Midsize         Sedan           24        17        3105  2000  
18      Midsize         Sedan           24        17        3105  2000  
19      Midsize         Wagon           20        16        3105  2000  
20      Midsize         Sedan           24        17        3105  2000  
21      Midsize         Sedan           21        16        3105  2000

In [35]:
audi["Model"].nunique()

34

## Question 5:

In [68]:
# How many columns in the dataset have missing values?
cars_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11914 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

There are 5 variables with missing values.

## Question 6:

In [41]:
# 1. Find the median value of "Engine Cylinders" column in the dataset.
cars_price["Engine Cylinders"].median()

6.0

In [59]:
# 2. Next, calculate the most frequent value of the same "Engine Cylinders"
cars_price["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

The most frequent value of `Engine Cylinder` is 4.0

In [64]:
# 3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
cars_price["Engine Cylinders"] = cars_price["Engine Cylinders"].fillna(value=cars_price["Engine Cylinders"].value_counts().index.values[0])

In [65]:
cars_price["Engine Cylinders"].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [66]:
cars_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11914 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [67]:
# 4. Now, calculate the median value of "Engine Cylinders" once again.
cars_price["Engine Cylinders"].median()

6.0

## Question 7:

In [75]:
# 1. Select all the "Lotus" cars from the dataset.
# 2. Select only columns "Engine HP", "Engine Cylinders".
lotus = cars_price.loc[cars_price["Make"] == "Lotus", ["Engine HP", "Engine Cylinders"]]
lotus.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [76]:
# 3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
lotus.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 3912 to 4297
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Engine HP         29 non-null     float64
 1   Engine Cylinders  29 non-null     float64
dtypes: float64(2)
memory usage: 696.0 bytes


In [81]:
lotus = lotus.drop_duplicates()
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [82]:
# 4. Get the underlying NumPy array. Let's call it X
X = lotus.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [88]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. 
# Let's call the result XTX.
XTX = np.matmul(X.T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [89]:
# 6. Invert XTX
inv_XTX = np.linalg.inv(XTX)

In [90]:
# 7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [91]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = np.matmul(np.matmul(inv_XTX, X.T),y)
w

array([  4.59494481, -63.56432501])